drop table room_info;
CREATE TABLE room_info (
id int(10) NOT NULL auto_increment,
title varchar(255) NOT NULL default '',
room_name varchar(255) NOT NULL default '',
room_sort int(1) default NULL,
build_sort int(1) default NULL,
main_area varchar(20) default NULL,
area_fast varchar(20) default NULL,
area_code_1 varchar(2) default '00',
area_code_2 varchar(4) default '0000',
area_code_3 varchar(255) default NULL,
cate_code_1 varchar(6) default NULL,
line_code varchar(2) default '00',
station_code varchar(4) default '0000',
walk_time int(2) default NULL,
room_fee varchar(10) default NULL,
fee_unit varchar(10) default NULL,
equipment_fee varchar(10) default NULL,
deposit_fee varchar(10) default NULL,
entrance_fee varchar(10) default NULL,
room_type varchar(11) default NULL,
sex int(1) default NULL,
url varchar(255) default NULL,
email varchar(50) NOT NULL default '',
tel_no1_1 varchar(4) default NULL,
tel_no1_2 varchar(4) default NULL,
tel_no1_3 varchar(4) default NULL,
tel_no2_1 varchar(4) default NULL,
tel_no2_2 varchar(4) default NULL,
tel_no2_3 varchar(4) default NULL,
photo_name1 varchar(50) default NULL,
photo_name2 varchar(50) default NULL,
photo_name3 varchar(50) default NULL,
photo_name4 varchar(50) default NULL,
photo_name5 varchar(50) default NULL,
user_id varchar(20) default NULL,
 regist_date timestamp NOT NULL,
 update_date timestamp NOT NULL,
read_count int(4) default NULL,
detail_info text NOT NULL,
deleteflg char(1) default '0',
PRIMARY KEY  (id)
) TYPE=MyISAM;
