drop table engineer;
CREATE TABLE `engineer` (                               
            `eng_id` int(10) NOT NULL auto_increment,             
            `eng_type` int(1) NOT NULL default '0',               
            `eng_initial` varchar(20) NOT NULL default '',        
            `eng_name1` varchar(30) NOT NULL default '',          
            `eng_name2` varchar(30) NOT NULL default '',          
            `eng_sex` char(1) default NULL,                       
            `eng_nation` int(1) default '0',                      
            `eng_nation_etc` varchar(250) NOT NULL default '',    
            `eng_skilllicense` varchar(100) default NULL,         
            `eng_japlicense` varchar(100) default NULL,           
            `eng_age` char(3) NOT NULL default '0',               
            `eng_career` char(2) NOT NULL default '0',            
            `eng_os` int(4) NOT NULL default '0',                 
            `eng_os_etc` varchar(250) default NULL,               
            `eng_db` int(4) NOT NULL default '0',                 
            `eng_db_etc` varchar(250) default NULL,               
            `eng_language` int(6) NOT NULL default '0',           
            `eng_language_etc` varchar(250) default NULL,         
            `eng_process` int(10) NOT NULL default '0',           
            `eng_possibledate` varchar(10) default NULL,          
            `eng_japanese` int(1) NOT NULL default '0',           
            `eng_ment` varchar(250) default NULL,                 
            `eng_salary` varchar(5) default NULL,                 
            `eng_state` varchar(100) default NULL,                
            `eng_filename` varchar(50) default NULL,              
            `eng_insertdate` date NOT NULL default '0000-00-00',  
            `eng_updatedate` date default NULL,                   
            `eng_id_position` varchar(30) NOT NULL default '',    
            `view_flg` char(1) default NULL,                      
            PRIMARY KEY  (`eng_id`)                               
          ) TYPE=MyISAM                                            
