 Drop table t_area;
 CREATE TABLE t_area (area_code_1 varchar(2)  NOT NULL ,
 area_code_2 varchar(4)  NOT NULL , 
 area_name_1 varchar(200)  NOT NULL ,
 area_name_2 varchar(200)  NOT NULL , 
 PRIMARY KEY  (area_code_1,area_code_2)) TYPE=MyISAM;

Drop table buysell_info;
CREATE TABLE buysell_info (
id int(10) NOT NULL auto_increment,
user_id varchar(10) NOT NULL default '',
title varchar(255) default NULL,
price varchar(255) default NULL,
price_unit int(1) default NULL,
pro_status int(1) default NULL,                          
send_method int(1) default NULL,
member_sort int(1) default NULL,
sell_place varchar(255) default NULL,
tel_no1_1 varchar(4) default NULL,       
tel_no1_2 varchar(4) default NULL,
tel_no1_3 varchar(4) default NULL,
tel_no2_1 varchar(4) default NULL,
tel_no2_2 varchar(4) default NULL,
tel_no2_3 varchar(4) default NULL,
free_price int(1) default NULL,
email varchar(255) default NULL,
detail_info text,
photo_name1 varchar(255) default NULL,
photo_name2 varchar(255) default NULL,
photo_name3 varchar(255) default NULL,
photo_name4 varchar(255) default NULL,
photo_name5 varchar(255) default NULL,
cate_code_1 varchar(6) default NULL,
cate_code_2 varchar(6) default NULL,
regist_date timestamp NOT NULL,
update_date timestamp NOT NULL,
read_count int(100) default NULL,
deleteflg char(1) default '0',
PRIMARY KEY  (id)

) TYPE=MyISAM;                             

drop table constant;
create table constant (
idx int(3) not null,
constance_name varchar(100) not null,
constance_value varchar(200),
constance_sort int(3),
PRIMARY KEY (constance_name)
);

Drop table contactus_info;
CREATE TABLE contactus_info (
id int(10) NOT NULL auto_increment,
name varchar(255) default NULL,
email varchar(255) default NULL,
tel_no1_1 varchar(4) default NULL,
tel_no1_2 varchar(4) default NULL,
tel_no1_3 varchar(4) default NULL,
tel_no2_1 varchar(4) default NULL,
tel_no2_2 varchar(4) default NULL,
tel_no2_3 varchar(4) default NULL,
title varchar(255) default NULL,
detail_info text,
regist_date timestamp NOT NULL,
update_date timestamp NOT NULL,
deleteflg char(1) default '0',
PRIMARY KEY  (id)
) TYPE=MyISAM;

Drop table findjob_info;
CREATE TABLE findjob_info (
id int(11) NOT NULL auto_increment,
user_id varchar(40) default NULL,
title varchar(255) default NULL,
tel_no1_1 varchar(4) default NULL,
tel_no1_2 varchar(4) default NULL,
tel_no1_3 varchar(4) default NULL,
tel_no2_1 varchar(4) default NULL,
tel_no2_2 varchar(4) default NULL,
tel_no2_3 varchar(4) default NULL,
email varchar(255) default NULL,
work_sort int(1) default NULL,
birthday varchar(10) default NULL,
sex int(1) default NULL,
appeal_point text default NULL,
detail_info text default NULL,
regist_date timestamp NOT NULL,
update_date timestamp NOT NULL,
read_count int(100) default NULL,
deleteflg char(1) default '0',
PRIMARY KEY  (id)
)TYPE=MyISAM;

Drop table gourmet_info;
CREATE TABLE gourmet_info (
id int(11) NOT NULL auto_increment,
user_id varchar(40) default NULL,
store_name_k varchar(255) default NULL,
store_name_j varchar(255) default NULL,
search_word varchar(255) default NULL,
store_name_open int(1) default NULL,
tel_no1_1 varchar(4) default NULL,
tel_no1_2 varchar(4) default NULL,
tel_no1_3 varchar(4) default NULL,
tel_no2_1 varchar(4) default NULL,
tel_no2_2 varchar(4) default NULL,
tel_no2_3 varchar(4) default NULL,
tel_no_1_open int(1) default NULL,
tel_no_2_open int(1) default NULL,
fax_no_1 varchar(4) default NULL,
fax_no_2 varchar(4) default NULL,
fax_no_3 varchar(4) default NULL,
fax_no_open int(1) default NULL,
email varchar(255) default NULL,
email_open int(1) default NULL,
url varchar(255) default NULL,
photo_name1 varchar(255) default NULL,
photo_name2 varchar(255) default NULL,
photo_name3 varchar(255) default NULL,
photo_name4 varchar(255) default NULL,
photo_name5 varchar(255) default NULL,
main_area char(1) default NULL,
area_code_1 varchar(2) default '00',
area_code_2 varchar(4) default '0000',
area_code_3 varchar(255) default NULL,
area_code_open int(1) default NULL,
line_code varchar(2) default '00',
station_code varchar(4) default '0000',
area_fast varchar(64) default NULL,
sort_code varchar(64) default NULL,
cate_code_1 varchar(6) default NULL,
cate_code_2 varchar(6) default NULL,
view_code varchar(64) default NULL,
appeal_point text default NULL,
work_time varchar(255) default NULL,
rest_day varchar(255) default NULL,
detail_info text default NULL,
regist_date timestamp NOT NULL,
update_date timestamp NOT NULL,
read_count int(100) default NULL,
deleteflg char(1) default '0',
PRIMARY KEY(id)
)TYPE=MyISAM;

Drop table house_info;
CREATE TABLE house_info (                                  
id int(10) NOT NULL auto_increment,
title varchar(255) NOT NULL default '',
house_name varchar(255) NOT NULL default '',
detail_info text NOT NULL,
email varchar(255) default NULL,
tel_no1_1 varchar(4) default NULL,
tel_no1_2 varchar(4) default NULL,
tel_no1_3 varchar(4) default NULL,
tel_no2_1 varchar(4) default NULL,
tel_no2_2 varchar(4) default NULL,
tel_no2_3 varchar(4) default NULL,
manage_fee int(10) default NULL,
house_sort char(1) default NULL,
dimension int(5) default NULL,
house_fee int(10) default NULL,
deposit varchar(10) default NULL,
reikin varchar(10) default NULL,
walk_time int(2) default NULL,
build_year varchar(50) default NULL,
madori varchar(10) default NULL,
all_stairs varchar(10) default NULL,
stairs varchar(10) default NULL,
flg_tadami char(1) default NULL,
toilet char(1) default NULL,
line_code varchar(2) default '00',
station_code varchar(4) default '0000',
photo_name1 varchar(255) default NULL,
photo_name2 varchar(255) default NULL,
photo_name3 varchar(255) default NULL,
photo_name4 varchar(255) default NULL,
photo_name5 varchar(255) default NULL,
area_code_1 varchar(2) default '00',
area_code_2 varchar(4) default '0000',
area_code_3 varchar(255) default NULL,
area_fast varchar(20) default NULL,
main_area varchar(20) default NULL,
point_compass char(1) default NULL,
come_dock varchar(20) default NULL,
come_dock_year varchar(20) default NULL,
come_dock_month varchar(4) default NULL,
build_month varchar(10) default NULL,
guaranty_money varchar(10) default NULL,
house_option varchar(255) default NULL,
madori_info char(1) default NULL,
user_id varchar(255) NOT NULL default '',
regist_date timestamp NOT NULL,
update_date timestamp NOT NULL,
read_count int(10) default '0',
deleteflg char(1) default '0',
PRIMARY KEY  (id)
) TYPE=MyISAM;

Drop table job_info;
CREATE TABLE job_info (
id int(11) NOT NULL auto_increment,
user_id varchar(40) default NULL,
company_name_k varchar(255) default NULL,
company_name_j varchar(255) default NULL,
search_word varchar(255) default NULL,
company_name_open int(1) default NULL,
title varchar(255) default NULL,
charge varchar(255) default NULL,
pay varchar(255) default NULL,
work_time varchar(255) default NULL,
sex int(1) default NULL,
tel_no1_1 varchar(4) default NULL,
tel_no1_2 varchar(4) default NULL,
tel_no1_3 varchar(4) default NULL,
tel_no2_1 varchar(4) default NULL,
tel_no2_2 varchar(4) default NULL,
tel_no2_3 varchar(4) default NULL,
tel_no_1_open int(1) default NULL,
tel_no_2_open int(1) default NULL,
fax_no_1 varchar(4) default NULL,
fax_no_2 varchar(4) default NULL,
fax_no_3 varchar(4) default NULL,
fax_no_open int(1) default NULL,
email varchar(255) default NULL,
email_open int(1) default NULL,
url varchar(255) default NULL,
photo_name1 varchar(255) default NULL,
photo_name2 varchar(255) default NULL,
photo_name3 varchar(255) default NULL,
photo_name4 varchar(255) default NULL,
photo_name5 varchar(255) default NULL,
main_area char(1) default NULL,
area_code_1 varchar(2) default '00',
area_code_2 varchar(4) default '0000',
area_code_3 varchar(255) default NULL,
area_code_open int(1) default NULL,
line_code varchar(2) default '00',
station_code varchar(4) default '0000',
area_fast varchar(64) default NULL,
sort_code varchar(64) default NULL,
cate_code_1 varchar(6) default NULL,
cate_code_2 varchar(6) default NULL,
view_code varchar(64) default NULL,
appeal_point text default NULL,
detail_info text default NULL,
read_count int(100) default NULL,
regist_date timestamp NOT NULL,
update_date timestamp NOT NULL,
deleteflg char(1) default '0',
PRIMARY KEY (id)
) TYPE=MyISAM;

drop table member;
CREATE TABLE member (
user_id varchar(20) NOT NULL default '',
password varchar(20) default NULL,
email1 varchar(100) default NULL,
email2 varchar(100) default NULL,
name varchar(100) default NULL,
telephone1 varchar(4) default NULL,
telephone2 varchar(4) default NULL,
telephone3 varchar(4) default NULL,
mobile1 varchar(4) default NULL,
mobile2 varchar(4) default NULL,
mobile3 varchar(4) default NULL,
address varchar(200) default NULL,
user_level char(1) default '0',
registnum varchar(20) default '',
registflg char(1) default '0',
deleteflg char(1) default '0',
PRIMARY KEY  (user_id)
) TYPE=InnoDB;

drop table room_info;
CREATE TABLE room_info (
id int(10) NOT NULL auto_increment,
title varchar(255) NOT NULL default '',
room_name varchar(255) NOT NULL default '',
room_sort int(1) default NULL,
build_sort int(1) default NULL,
main_area varchar(20) default NULL,
area_fast varchar(20) default NULL,
area_code_1 varchar(2) default '00',
area_code_2 varchar(4) default '0000',
area_code_3 varchar(255) default NULL,
cate_code_1 varchar(6) default NULL,
line_code varchar(2) default '00',
station_code varchar(4) default '0000',
walk_time int(2) default NULL,
room_fee varchar(10) default NULL,
fee_unit varchar(10) default NULL,
equipment_fee varchar(10) default NULL,
deposit_fee varchar(10) default NULL,
entrance_fee varchar(10) default NULL,
room_type varchar(11) default NULL,
sex int(1) default NULL,
url varchar(255) default NULL,
email varchar(50) NOT NULL default '',
tel_no1_1 varchar(4) default NULL,
tel_no1_2 varchar(4) default NULL,
tel_no1_3 varchar(4) default NULL,
tel_no2_1 varchar(4) default NULL,
tel_no2_2 varchar(4) default NULL,
tel_no2_3 varchar(4) default NULL,
photo_name1 varchar(50) default NULL,
photo_name2 varchar(50) default NULL,
photo_name3 varchar(50) default NULL,
photo_name4 varchar(50) default NULL,
photo_name5 varchar(50) default NULL,
user_id varchar(20) default NULL,
 regist_date timestamp NOT NULL,
 update_date timestamp NOT NULL,
read_count int(4) default NULL,
detail_info text NOT NULL,
deleteflg char(1) default '0',
PRIMARY KEY  (id)
) TYPE=MyISAM;


Drop table t_store_category;
CREATE TABLE t_store_category (
cate_code_1 varchar(6)  NOT NULL ,
cate_code_2 varchar(6)  NOT NULL ,
category_name_1 varchar(255)  NOT NULL ,
category_name_1_detail varchar(255)  default NULL,
category_name_2 varchar(255)  NOT NULL ,
category_name_2_detail varchar(255) default NULL,
PRIMARY KEY  (cate_code_1,cate_code_2)
) TYPE=MyISAM;

Drop table store_info;
CREATE TABLE store_info (
id int(11) NOT NULL auto_increment,
user_id varchar(40) default NULL,
store_name_k varchar(255) default NULL,
store_name_j varchar(255) default NULL,
search_word varchar(255) default NULL,
store_name_open int(1) default NULL,
tel_no1_1 varchar(4) default NULL,
tel_no1_2 varchar(4) default NULL,
tel_no1_3 varchar(4) default NULL,
tel_no2_1 varchar(4) default NULL,
tel_no2_2 varchar(4) default NULL,
tel_no2_3 varchar(4) default NULL,
tel_no_1_open int(1) default NULL,
tel_no_2_open int(1) default NULL,
fax_no_1 varchar(4) default NULL,
fax_no_2 varchar(4) default NULL,
fax_no_3 varchar(4) default NULL,
fax_no_open int(1) default NULL,
email varchar(255) default NULL,
email_open int(1) default NULL,
url varchar(255) default NULL,
photo_name1 varchar(255) default NULL,
photo_name2 varchar(255) default NULL,
photo_name3 varchar(255) default NULL,
photo_name4 varchar(255) default NULL,
photo_name5 varchar(255) default NULL,
main_area char(1) default NULL,
area_code_1 varchar(2) default '00',
area_code_2 varchar(4) default '0000',
area_code_3 varchar(255) default NULL,
area_code_open int(1) default NULL,
line_code varchar(2) default '00',
station_code varchar(4) default '0000',
area_fast varchar(64) default NULL,
sort_code varchar(64) default NULL,
cate_code_1 varchar(6) default NULL,
cate_code_2 varchar(6) default NULL,
view_code varchar(64) default NULL,
appeal_point text default NULL,
work_time varchar(255) default NULL,
rest_day varchar(255) default NULL,
detail_info text default NULL,
read_count int(100) default NULL,
regist_date timestamp NOT NULL,
update_date timestamp NOT NULL,
deleteflg char(1) default '0',
PRIMARY KEY (id)
) TYPE=MyISAM;

Drop table t_buysell_category;
CREATE TABLE t_buysell_category (
cate_code_1 varchar(6)  NOT NULL ,
cate_code_2 varchar(6)  NOT NULL ,
category_name_1 varchar(255)  NOT NULL ,
category_name_1_detail varchar(255) ,
category_name_2 varchar(255)  ,
category_name_2_detail varchar(255)  ,
PRIMARY KEY  (cate_code_1,cate_code_2)
) TYPE=MyISAM;

Drop table t_gourmet_category;
CREATE TABLE t_gourmet_category (
cate_code_1 varchar(6)  NOT NULL ,
cate_code_2 varchar(6)  NOT NULL ,
category_name_1 varchar(255)  ,
category_name_1_detail varchar(255) ,
category_name_2 varchar(255)  ,
category_name_2_detail varchar(255) ,
PRIMARY KEY  (cate_code_1,cate_code_2)
) TYPE=MyISAM;

Drop table t_job_category;
CREATE TABLE t_job_category (
cate_code_1 varchar(6)  NOT NULL ,
cate_code_2 varchar(6)  NOT NULL ,
category_name_1 varchar(255)  ,
category_name_1_detail varchar(255)  ,
category_name_2 varchar(255)  ,
category_name_2_detail varchar(255)  ,
PRIMARY KEY  (cate_code_1,cate_code_2)
) TYPE=MyISAM;

Drop table t_train;
CREATE TABLE t_train (
station_code varchar(4)  NOT NULL ,
station_kanji varchar(200) ,
station_kana varchar(200)  ,
line_code varchar(2)  NOT NULL ,
line_kanji varchar(200)  ,
line_kana varchar(200)  ,
PRIMARY KEY  (station_code)
) TYPE=MyISAM;
