Drop table interpret_info;
CREATE TABLE `interpret_info` (                                   
                  `id` int(11) NOT NULL auto_increment,                           
                  `user_id` varchar(20) NOT NULL default '',                      
                  `name_open` int(1) default NULL,                                
                  `language` varchar(4) NOT NULL default '',                      
                  `language_etc` varchar(100) default NULL,                       
                  `service_area_1` varchar(4) NOT NULL default '',                
                  `service_area_1_etc` varchar(100) default NULL,                 
                  `service_area_2` varchar(100) default NULL,                     
                  `sex` char(1) default NULL,                                     
                  `birthday` varchar(6) default NULL,                             
                  `nation` varchar(4) default NULL,                               
                  `nation_etc` varchar(100) default NULL,                         
                  `photo_path` varchar(255) default NULL,                         
                  `photo_path_open` int(1) default NULL,                          
                  `resume_path` varchar(255) default NULL,                        
                  `resume_path_open` int(1) default NULL,                         
                  `nation_no` varchar(4) default NULL,                            
                  `tel_no_1` varchar(14) default NULL,                            
                  `tel_no_2` varchar(14) default NULL,                            
                  `tel_no_1_open` int(1) default NULL,                            
                  `tel_no_2_open` int(1) default NULL,                            
                  `pay` varchar(9) default NULL,                                  
                  `pay_unit` char(1) default NULL,                                
                  `pay_unit_etc` varchar(50) default NULL,                        
                  `service_day` text,                                             
                  `service_day_open` int(1) default NULL,                         
                  `certification` text,                                           
                  `certification_open` int(1) default NULL,                       
                  `skill` text,                                                   
                  `skill_open` int(1) default NULL,                               
                  `introduction` text,                                            
                  `introduction_open` int(1) default NULL,                        
                  `etc` text,                                                     
                  `etc_open` int(1) default NULL,                                 
                  `regist_date` timestamp(14) NOT NULL,                           
                  `update_date` timestamp(14) NOT NULL default '00000000000000',  
                  `viewflg` char(1) default '0',  
                   `deleteflg` char(1) default '0',                                
                  PRIMARY KEY  (`id`)                                             
                ) TYPE=MyISAM     