Drop table nihongo_info;
CREATE TABLE nihongo_info (
id int(11) NOT NULL auto_increment,
user_id varchar(40) default NULL,
school_name_k varchar(255) default NULL,
school_name_j varchar(255) default NULL,
area_code1 varchar(2) default '00',
area_code2 varchar(4) default '0000',
area_info varchar(255) default NULL,
zip_code1 varchar(3) default NULL,
zip_code2 varchar(4) default NULL,
line_code varchar(2) default '00',
station_code varchar(4) default '0000',
tel_no_1 varchar(4) default NULL,
tel_no_2 varchar(4) default NULL,
tel_no_3 varchar(4) default NULL,
fax_no_1 varchar(4) default NULL,
fax_no_2 varchar(4) default NULL,
fax_no_3 varchar(4) default NULL,
url varchar(255) default NULL,
email varchar(255) default NULL,
registrationfee_1 int(10) default NULL,
registrationfee_3 int(10) default NULL,
registrationfee_6 int(10) default NULL,
registrationfee_12 int(10) default NULL,
entrancefee_1 int(10) default NULL,
entrancefee_3 int(10) default NULL,
entrancefee_6 int(10) default NULL,
entrancefee_12 int(10) default NULL,
lessonsfee_1 int(10) default NULL,
lessonsfee_3 int(10) default NULL,
lessonsfee_6 int(10) default NULL,
lessonsfee_12 int(10) default NULL,
totalfee_1 int(10) default NULL,
totalfee_3 int(10) default NULL,
totalfee_6 int(10) default NULL,
totalfee_12 int(10) default NULL,
studentsu_korean int(10) default NULL,
studentsu_chinese int(10) default NULL,
studentsu_others int(10) default NULL,
studentsu_total int(10) default NULL,
dormitoryflg char (1) default NULL,
feature text default NULL,
photo_name1 varchar(255) default NULL,
photo_name2 varchar(255) default NULL,
photo_name3 varchar(255) default NULL,
photo_name4 varchar(255) default NULL,
photo_name5 varchar(255) default NULL,
read_count int(100) default NULL,
regist_date timestamp NOT NULL,
update_date timestamp NOT NULL,
deleteflg char(1) default '0',
PRIMARY KEY (id)
) TYPE=MyISAM;