Drop table house_info;
CREATE TABLE house_info (
id int(10) NOT NULL auto_increment,                         
info_id varchar(255) NOT NULL ,
title varchar(255) NOT NULL default '',
house_name varchar(255) NOT NULL default '',
detail_info text NOT NULL,
email varchar(255) default NULL,
tel_no1_1 varchar(4) default NULL,
tel_no1_2 varchar(4) default NULL,
tel_no1_3 varchar(4) default NULL,
tel_no2_1 varchar(4) default NULL,
tel_no2_2 varchar(4) default NULL,
tel_no2_3 varchar(4) default NULL,
manage_fee int(10) default NULL,
house_sort char(1) default NULL,
dimension DOUBLE(5,2) default NULL,
house_fee int(10) default NULL,
deposit varchar(10) default '0',
reikin varchar(10) default '0',
walk_time int(2) default NULL,
build_year varchar(50) default NULL,
madori char(1) default NULL,
all_stairs varchar(20) default NULL,
stairs varchar(10) default NULL,
flg_tadami char(1) default NULL,
toilet char(1) default NULL,
line_code varchar(2) default '00',
station_code varchar(4) default '0000',
photo_name1 varchar(255) default NULL,
photo_name2 varchar(255) default NULL,
photo_name3 varchar(255) default NULL,
photo_name4 varchar(255) default NULL,
photo_name5 varchar(255) default NULL,
area_code_1 varchar(2) default '00',
area_code_2 varchar(4) default '0000',
area_code_3 varchar(255) default NULL,
area_fast varchar(20) default NULL,
main_area varchar(20) default NULL,
point_compass char(1) default NULL,
come_dock varchar(20) default NULL,
come_dock_year varchar(20) default NULL,
come_dock_month varchar(4) default NULL,
build_month varchar(10) default NULL,
guaranty_money varchar(10) default NULL,
house_option varchar(255) default NULL,
madori_info varchar(255) default NULL,
detail_url varchar(500) default NULL,
info_company_id int(10) default NULL,
info_acquisition_site varchar(255) default NULL,
user_id varchar(255) NOT NULL default '',
regist_date timestamp NOT NULL,
update_date timestamp NOT NULL,
read_count int(10) default '0',
deleteflg char(1) default '0',
PRIMARY KEY  (id)
) TYPE=MyISAM;