Drop table buysell_info;
CREATE TABLE buysell_info (
id int(10) NOT NULL auto_increment,
user_id varchar(10) NOT NULL default '',
title varchar(255) default NULL,
price varchar(255) default NULL,
price_unit int(1) default NULL,
pro_status int(1) default NULL,                          
send_method int(1) default NULL,
member_sort int(1) default NULL,
sell_place varchar(255) default NULL,
tel_no1_1 varchar(4) default NULL,       
tel_no1_2 varchar(4) default NULL,
tel_no1_3 varchar(4) default NULL,
tel_no2_1 varchar(4) default NULL,
tel_no2_2 varchar(4) default NULL,
tel_no2_3 varchar(4) default NULL,
free_price int(1) default NULL,
email varchar(255) default NULL,
detail_info text,
photo_name1 varchar(255) default NULL,
photo_name2 varchar(255) default NULL,
photo_name3 varchar(255) default NULL,
photo_name4 varchar(255) default NULL,
photo_name5 varchar(255) default NULL,
cate_code_1 varchar(6) default NULL,
cate_code_2 varchar(6) default NULL,
regist_date timestamp NOT NULL,
update_date timestamp NOT NULL,
read_count int(100) default NULL,
deleteflg char(1) default '0',
PRIMARY KEY  (id)

) TYPE=MyISAM;                             