Drop table housefind_info;
CREATE TABLE `housefind_info` (                
                  `id` int(10) NOT NULL auto_increment,        
                  `title` varchar(255) NOT NULL default '',    
                  `user_id` varchar(255) NOT NULL default '',  
                  `email` varchar(50) default NULL,            
                  `telephone` varchar(20) default NULL,        
                  `detail_info` text NOT NULL,                 
                  `come_dock` varchar(20) default NULL,        
                  `come_dock_year` int(5) default NULL,        
                  `come_dock_month` int(5) default NULL,       
                  `house_fee_from` int(11) default NULL,       
                  `house_fee_to` int(11) default NULL,         
                  `area_code_1` varchar(20) default NULL,      
                  `area_code_2` varchar(20) default NULL,      
                  `area_fast` varchar(20) default NULL,        
                  `main_area` varchar(20) default NULL,        
                  `line_code` varchar(20) default NULL,        
                  `station_code` varchar(20) default NULL,     
                  `walk_time` int(10) default NULL,            
                  `house_sort` varchar(20) default NULL,       
                  `dimension_from` int(20) default NULL,       
                  `dimension_to` int(20) default NULL,         
                  `madori` varchar(20) default NULL,           
                  `regist_date` date default NULL,             
                  `update_date` date default NULL,             
                  `read_count` int(4) default '0',             
                  `deleteflg` char(1) default '0',             
                  PRIMARY KEY  (`id`)                          
                ) TYPE=MyISAM                                  
